#!/bin/sh

# Check vpn-tunnel "tun0" and ping cz.nic if internet connection work
if  [ "$(ping -I tun0 -q -c 1 -W 1 8.8.8.8 | grep '100% packet loss' )" != "" ]; then
        echo "tun0 has got no internet connectionection  restart it"
        sudo service openvpn restart
else
        echo "tun0 is working with internet connection"
fi
